### ISSUE TITLE
rom zip file checksums will likely never match

### ISSUE THREAD

**Issue by mdeslaur** [Phillrb/arkanoid_multi#1]
Your script checks the checksums of the zip file, but most MAME sites that host the roms insert their own txt file, or re-zip the files they host, so the zip file is unlikely to ever match the same checksum you have.

I suggest verifying the checksums of the rom files themselves.

**Comment by Phillrb** [comment]
This is now fixed. Thanks for pointing it out! I no longer validate the checksums of the 3 zip files but instead just check they are present. All the other checksums should be enough. Cheers.
